export interface Sheet {
	name: string;
	columns: Column[];
}

export interface Column {
	header: string;
	key: string;
	width?: number;
}

export const SHEETS: Sheet[] = [
	{
		name: 'Account',
		columns: [
			{ header: 'Account', key: 'name', width: 17 },
			{ header: 'Adspower Browser Id', key: 'adsPower.profileId' },
			{ header: 'Vision Token', key: 'vision.token' },
			{ header: 'Vision Folder Id', key: 'vision.folderId' },
			{ header: 'Vision Profile Id', key: 'vision.profileId' },
			{ header: 'Afina API Key', key: 'afina.apiKey' },
			{ header: 'Afina Profile Id', key: 'afina.profileId' },
			{ header: 'Proxy Type', key: 'proxy.type' },
			{ header: 'Proxy Ip', key: 'proxy.ip' },
			{ header: 'Proxy Port', key: 'proxy.port' },
			{ header: 'Proxy Login', key: 'proxy.login' },
			{ header: 'Proxy Password', key: 'proxy.password' },
			{ header: 'Proxy rotateUrl', key: 'proxy.rotateUrl' },
			{ header: 'Github token', key: 'github.token' },
		],
	},
	{
		name: 'Wallets',
		columns: [
			{ header: 'Account', key: 'name', width: 17 },
			{ header: 'EVM seed', key: 'wallets.evm.seed' },
			{ header: 'EVM private', key: 'wallets.evm.private' },
			{ header: 'EVM addr', key: 'wallets.evm.address' },
			{ header: 'Starknet seed', key: 'wallets.starknet.seed' },
			{ header: 'Starknet private', key: 'wallets.starknet.private' },
			{ header: 'Starknet addr', key: 'wallets.starknet.address' },
			{ header: 'Aptos seed', key: 'wallets.aptos.seed' },
			{ header: 'Aptos private', key: 'wallets.aptos.private' },
			{ header: 'Aptos addr', key: 'wallets.aptos.address' },
			{ header: 'Sui seed', key: 'wallets.sui.seed' },
			{ header: 'Sui private', key: 'wallets.sui.private' },
			{ header: 'Sui addr', key: 'wallets.sui.address' },
			{ header: 'Solana seed', key: 'wallets.solana.seed' },
			{ header: 'Solana private', key: 'wallets.solana.private' },
			{ header: 'Solana addr', key: 'wallets.solana.address' },
		],
	},
	{
		name: 'Cexs',
		columns: [
			{ header: 'Account', key: 'name', width: 17 },
			{ header: 'OKX email', key: 'cexs.okx.email' },
			{ header: 'OKX evmDepositAddress', key: 'cexs.okx.evmDepositAddress' },
			{ header: 'OKX solanaDepositAddress', key: 'cexs.okx.solanaDepositAddress' },
			{ header: 'OKX starknetDepositAddress', key: 'cexs.okx.starknetDepositAddress' },
			{ header: 'OKX suiDepositAddress', key: 'cexs.okx.suiDepositAddress' },
			{ header: 'OKX aptosDepositAddress', key: 'cexs.okx.aptosDepositAddress' },
			{ header: 'OKX secretKey', key: 'cexs.okx.api.secretKey' },
			{ header: 'OKX apiKey', key: 'cexs.okx.api.apiKey' },
			{ header: 'OKX passPhrase', key: 'cexs.okx.api.passPhrase' },
			{ header: 'Binance email', key: 'cexs.binance.email' },
			{ header: 'Binance evmDepositAddress', key: 'cexs.binance.evmDepositAddress' },
			{ header: 'Binance starknetDepositAddress', key: 'cexs.binance.starknetDepositAddress' },
			{ header: 'Binance suiDepositAddress', key: 'cexs.binance.suiDepositAddress' },
			{ header: 'Binance aptosDepositAddress', key: 'cexs.binance.aptosDepositAddress' },
			{ header: 'Binance secretKey', key: 'cexs.binance.api.secretKey' },
			{ header: 'Binance apiKey', key: 'cexs.binance.api.apiKey' },
			{ header: 'Binance passPhrase', key: 'cexs.binance.api.passPhrase' },
			{ header: 'Bitget email', key: 'cexs.bitget.email' },
			{ header: 'Bitget evmDepositAddress', key: 'cexs.bitget.evmDepositAddress' },
			{ header: 'Bitget solanaDepositAddress', key: 'cexs.bitget.solanaDepositAddress' },
			{ header: 'Bitget starknetDepositAddress', key: 'cexs.bitget.starknetDepositAddress' },
			{ header: 'Bitget suiDepositAddress', key: 'cexs.bitget.suiDepositAddress' },
			{ header: 'Bitget aptosDepositAddress', key: 'cexs.bitget.aptosDepositAddress' },
			{ header: 'Bitget secretKey', key: 'cexs.bitget.api.secretKey' },
			{ header: 'Bitget apiKey', key: 'cexs.bitget.api.apiKey' },
			{ header: 'Bitget passPhrase', key: 'cexs.bitget.api.passPhrase' },
		],
	},
	{
		name: 'Extensions',
		columns: [
			{ header: 'Account', key: 'name', width: 17 },
			{ header: 'Metamask password', key: 'extensions.metamask.password' },
			{ header: 'Metamask baseUrl', key: 'extensions.metamask.baseUrl' },
			{ header: 'Martian password', key: 'extensions.martian.password' },
			{ header: 'Martian baseUrl', key: 'extensions.martian.baseUrl' },
			{ header: 'Argent password', key: 'extensions.argent.password' },
			{ header: 'Argent baseUrl', key: 'extensions.argent.baseUrl' },
			{ header: 'SuiWallet password', key: 'extensions.suiWallet.password' },
			{ header: 'SuiWallet baseUrl', key: 'extensions.suiWallet.baseUrl' },
			{ header: 'ethosWallet password', key: 'extensions.ethosWallet.password' },
			{ header: 'ethosWallet baseUrl', key: 'extensions.ethosWallet.baseUrl' },
			{ header: 'petraWallet password', key: 'extensions.petraWallet.password' },
			{ header: 'petraWallet baseUrl', key: 'extensions.petraWallet.baseUrl' },
			{ header: 'Zerion password', key: 'extensions.zerion.password' },
			{ header: 'Zerion baseUrl', key: 'extensions.zerion.baseUrl' },
			{ header: 'Backpack password', key: 'extensions.backpack.password' },
			{ header: 'Backpack baseUrl', key: 'extensions.backpack.baseUrl' },
			{ header: 'Phantom password', key: 'extensions.phantom.password' },
			{ header: 'Phantom baseUrl', key: 'extensions.phantom.baseUrl' },
			{ header: 'Rabby password', key: 'extensions.rabby.password' },
			{ header: 'Rabby baseUrl', key: 'extensions.rabby.baseUrl' },
		],
	},
	{
		name: 'Twitter',
		columns: [
			{ header: 'Account', key: 'name', width: 17 },
			{ header: 'login', key: 'socials.twitter.login' },
			{ header: 'password', key: 'socials.twitter.password' },
			{ header: 'mail', key: 'socials.twitter.mail' },
			{ header: 'mailPassword', key: 'socials.twitter.mailPassword' },
			{ header: 'phone', key: 'socials.twitter.phone' },
			{ header: 'recoveryMail', key: 'socials.twitter.recoveryMail' },
			{ header: 'recoveryMailPassword', key: 'socials.twitter.recoveryMailPassword' },
			{ header: 'token', key: 'socials.twitter.token' },
			{ header: '_2fa', key: 'socials.twitter._2fa' },
		],
	},
	{
		name: 'Discord',
		columns: [
			{ header: 'Account', key: 'name', width: 17 },
			{ header: 'login', key: 'socials.discord.login' },
			{ header: 'password', key: 'socials.discord.password' },
			{ header: 'mail', key: 'socials.discord.mail' },
			{ header: 'mailPassword', key: 'socials.discord.mailPassword' },
			{ header: 'phone', key: 'socials.discord.phone' },
			{ header: 'recoveryMail', key: 'socials.discord.recoveryMail' },
			{ header: 'recoveryMailPassword', key: 'socials.discord.recoveryMailPassword' },
			{ header: 'token', key: 'socials.discord.token' },
			{ header: '_2fa', key: 'socials.discord._2fa' },
		],
	},
	{
		name: 'Mail',
		columns: [
			{ header: 'Account', key: 'name', width: 17 },
			{ header: 'login', key: 'socials.mail.login' },
			{ header: 'password', key: 'socials.mail.password' },
			{ header: 'mail', key: 'socials.mail.mail' },
			{ header: 'mailPassword', key: 'socials.mail.mailPassword' },
			{ header: 'phone', key: 'socials.mail.phone' },
			{ header: 'recoveryMail', key: 'socials.mail.recoveryMail' },
			{ header: 'recoveryMailPassword', key: 'socials.mail.recoveryMailPassword' },
			{ header: 'token', key: 'socials.mail.token' },
			{ header: '_2fa', key: 'socials.mail._2fa' },
		],
	},
];
