export interface ActionParams {
	group: ActionsGroupName;
	action: ActionName;
}

export enum ActionsGroupName {
	Common = 'Common',
	CommonUi = 'CommonUi',
	Evm = 'Evm',
	Svm = 'Svm',
	Towns = 'Towns',
	Twitter = 'Twitter',
	Eclipse = 'Eclipse',
	Okx = 'Okx',
	Bitget = 'Bitget',
	Binance = 'Binance',
	Gate = 'Gate',
	Odos = 'Odos',
	Berachain = 'Berachain',
	Opensea = 'Opensea',
	TEST = 'TEST',
	TEST_PREMIUM = 'TEST_PREMIUM',
	Hemi = 'Hemi',
	Shape = 'Shape',
	Plasma = 'Plasma',
	ZksyncLite = 'ZksyncLite',
	Sophon = 'Sophon',
}

export enum ActionName {
	CheckBalances = 'CheckBalances',
	CheckTransactions = 'CheckTransactions',
	RegisterUi = 'RegisterUi',
	Claim = 'Claim',
	ClaimUi = 'ClaimUi',
	Bober = 'Bober',
	OpenPages = 'OpenPages',
	Follow = 'Follow',
	Tap = 'Tap',
	Review = 'Review',
	JoinTown = 'JoinTown',
	RandomActionInRandomChannelInNativeTown = 'RandomActionInRandomChannelInNativeTown',
	RandomActionInRandomChannelInRandomTown = 'RandomActionInRandomChannelInRandomTown',
	SendToken = 'SendToken',
	LikeAndRetweet = 'LikeAndRetweet',
	Login = 'Login',
	ChangeName = 'ChangeName',
	Withdraw = 'Withdraw',
	CheckNft = 'CheckNft',
	Swap = 'Swap',
	HoneypotSwap = 'HoneypotSwap',
	HoneyfunCreateMeme = 'HoneyfunCreateMeme',
	HoneyfunSellAllMemes = 'HoneyfunSellAllMemes',
	EtherfiConfirmNetwork = 'EtherfiConfirmNetwork',
	OpenseaBuyByLink = 'OpenseaBuyByLink',
	Register = 'Register',
	LombardDepositBase = 'LombardDepositBase',
	LombardDepositSonic = 'LombardDepositSonic',
	Wrap = 'Wrap',
	Unwrap = 'Unwrap',
	CheckStats = 'CheckStats',
	DapDap = 'DapDap',
	KodiakSwap = 'KodiakSwap',
	TEST = 'TEST',
	ShowWallets = 'ShowWallets',
	RefuelManyGasZip = 'RefuelManyGasZip',
	RefuelManyRelayLink = 'RefuelManyRelayLink',
	Approve = 'Approve',
	WithdrawFlow = 'WithdrawFlow',
	Outpostsurge = 'Outpostsurge',
	JunkyUrsas = 'JunkyUrsas',
	CrosschainMint = 'CrosschainMint',
	Yeet = 'Yeet',
	YeetGetTodayValues = 'YeetGetTodayValues',
	Reply = 'Reply',
	RefuelGasZip = 'RefuelGasZip',
	RefuelRelayLink = 'RefuelRelayLink',
	SweepByLink = 'SweepByLink',
	MintStack = 'MintStack',
	MintForms = 'MintForms',
	ConnectTwitter = 'ConnectTwitter',
	ConnectDiscord = 'ConnectDiscord',
	RestoreMetamask = 'RestoreMetamask',
	RestorePetra = 'RestorePetra',
	OtomMint = 'OtomMint',
	OtomAnnihilate = 'OtomAnnihilate',
	OtomAnalyze = 'OtomAnalyze',
	OtomMineAllOtoms = 'OtomMineAllOtoms',
	OtomMineOtom = 'OtomMineOtom',
	OtomMineAndAnnihilateMolecule = 'OtomMineAndAnnihilateMolecule',
	Mint = 'Mint',
	OtomMineMolecule = 'OtomMineMolecule',
	GetProfileInfo = 'GetProfileInfo',
	OnetLogin = 'OnetLogin',
	LoginByToken = 'LoginByToken',
	OutlookLogin = 'OutlookLogin',
	OtomCraftPkax = 'OtomCraftPkax',
	ClaimBgtAndRedeemAndSendToOkx = 'ClaimBgtAndRedeemAndSendToOkx',
	FlyTradeSwap = 'FlyTradeSwap',
	MakeTransaction = 'MakeTransaction',
	Deposit = 'Deposit',
	GenerateWallets = 'GenerateWallets',
	RestoreBackpack = 'RestoreBackpack',
	RestoreArgent = 'RestoreArgent',
	GetProfiles = 'GetProfiles',
	LoginInMetamask = 'LoginInMetamask',
	LoginInRabby = 'LoginInRabby',
	RestoreRabby = 'RestoreRabby',
	SellCollectionByLink = 'SellCollectionByLink',
}

export interface Action {
	action: ActionName;
	isolated: boolean;
}

export interface ActionsGroup {
	group: ActionsGroupName;
	premium: boolean;
	actions: Action[];
}

export const ACTIONS: ActionsGroup[] = [
	{
		group: ActionsGroupName.Common,
		premium: false,
		actions: [
			{ action: ActionName.CheckBalances, isolated: false },
			{ action: ActionName.GenerateWallets, isolated: false },
			{ action: ActionName.RefuelGasZip, isolated: true },
			{ action: ActionName.RefuelRelayLink, isolated: true },
			{ action: ActionName.RefuelManyGasZip, isolated: false },
			{ action: ActionName.RefuelManyRelayLink, isolated: false },
		],
	},
	{
		group: ActionsGroupName.Evm,
		premium: false,
		actions: [
			{ action: ActionName.SendToken, isolated: true },
			{ action: ActionName.CheckNft, isolated: false },
			{ action: ActionName.CheckTransactions, isolated: true },
			{ action: ActionName.Wrap, isolated: true },
			{ action: ActionName.Unwrap, isolated: true },
			{ action: ActionName.Approve, isolated: true },
			{ action: ActionName.MakeTransaction, isolated: true },
		],
	},
	{
		group: ActionsGroupName.Svm,
		premium: false,
		actions: [{ action: ActionName.SendToken, isolated: true }],
	},
	{
		group: ActionsGroupName.Twitter,
		premium: false,
		actions: [
			{ action: ActionName.Follow, isolated: true },
			{ action: ActionName.LikeAndRetweet, isolated: true },
			{ action: ActionName.Login, isolated: true },
			{ action: ActionName.LoginByToken, isolated: true },
			{ action: ActionName.OnetLogin, isolated: true },
			{ action: ActionName.OutlookLogin, isolated: true },
			{ action: ActionName.ChangeName, isolated: true },
			{ action: ActionName.GetProfileInfo, isolated: true },
			{ action: ActionName.Reply, isolated: true },
		],
	},
	{
		group: ActionsGroupName.Okx,
		premium: false,
		actions: [{ action: ActionName.Withdraw, isolated: true }],
	},
	{
		group: ActionsGroupName.Bitget,
		premium: false,
		actions: [{ action: ActionName.Withdraw, isolated: true }],
	},
	{
		group: ActionsGroupName.Binance,
		premium: false,
		actions: [{ action: ActionName.Withdraw, isolated: true }],
	},
	{
		group: ActionsGroupName.Gate,
		premium: false,
		actions: [{ action: ActionName.Withdraw, isolated: true }],
	},
	{
		group: ActionsGroupName.Odos,
		premium: false,
		actions: [{ action: ActionName.Swap, isolated: true }],
	},
	{
		group: ActionsGroupName.TEST,
		premium: false,
		actions: [{ action: ActionName.TEST, isolated: true }],
	},
	{
		group: ActionsGroupName.ZksyncLite,
		premium: true,
		actions: [{ action: ActionName.SendToken, isolated: true }],
	},
	{
		group: ActionsGroupName.TEST_PREMIUM,
		premium: true,
		actions: [{ action: ActionName.TEST, isolated: true }],
	},
	{
		group: ActionsGroupName.CommonUi,
		premium: true,
		actions: [
			{ action: ActionName.OpenPages, isolated: true },
			{ action: ActionName.GetProfiles, isolated: false },
			{ action: ActionName.LoginInMetamask, isolated: true },
			{ action: ActionName.RestoreMetamask, isolated: true },
			{ action: ActionName.RestorePetra, isolated: true },
			{ action: ActionName.RestoreBackpack, isolated: true },
			{ action: ActionName.RestoreArgent, isolated: true },
			{ action: ActionName.LoginInRabby, isolated: true },
			{ action: ActionName.RestoreRabby, isolated: true },
		],
	},
	{
		group: ActionsGroupName.Towns,
		premium: true,
		actions: [
			{ action: ActionName.Bober, isolated: true },
			{ action: ActionName.JoinTown, isolated: true },
			{ action: ActionName.RandomActionInRandomChannelInNativeTown, isolated: true },
			{ action: ActionName.RandomActionInRandomChannelInRandomTown, isolated: true },
			{ action: ActionName.Review, isolated: true },
		],
	},
	{
		group: ActionsGroupName.Eclipse,
		premium: true,
		actions: [
			{ action: ActionName.Tap, isolated: true },
			{ action: ActionName.Withdraw, isolated: true },
		],
	},
	{
		group: ActionsGroupName.Berachain,
		premium: true,
		actions: [
			{ action: ActionName.HoneypotSwap, isolated: true },
			{ action: ActionName.HoneyfunCreateMeme, isolated: true },
			{ action: ActionName.HoneyfunSellAllMemes, isolated: true },
			{ action: ActionName.DapDap, isolated: true },
			{ action: ActionName.KodiakSwap, isolated: true },
			{ action: ActionName.JunkyUrsas, isolated: true },
			{ action: ActionName.ClaimBgtAndRedeemAndSendToOkx, isolated: true },
			{ action: ActionName.FlyTradeSwap, isolated: true },
			{ action: ActionName.CheckStats, isolated: true },
			{ action: ActionName.Outpostsurge, isolated: true },
			{ action: ActionName.Yeet, isolated: true },
			{ action: ActionName.YeetGetTodayValues, isolated: true },
		],
	},
	{
		group: ActionsGroupName.Opensea,
		premium: true,
		actions: [
			{ action: ActionName.OpenseaBuyByLink, isolated: true },
			{ action: ActionName.ClaimUi, isolated: true },
			{ action: ActionName.SweepByLink, isolated: true },
			{ action: ActionName.SellCollectionByLink, isolated: true },
			{ action: ActionName.Register, isolated: true },
			{ action: ActionName.CrosschainMint, isolated: true },
			{ action: ActionName.Mint, isolated: true },
		],
	},
	{
		group: ActionsGroupName.Shape,
		premium: true,
		actions: [
			{ action: ActionName.MintStack, isolated: true },
			{ action: ActionName.MintForms, isolated: true },
			{ action: ActionName.Claim, isolated: true },
			{ action: ActionName.ConnectTwitter, isolated: true },
			{ action: ActionName.ConnectDiscord, isolated: true },
			{ action: ActionName.CheckStats, isolated: true },
			{ action: ActionName.OtomMint, isolated: true },
			{ action: ActionName.OtomAnnihilate, isolated: true },
			{ action: ActionName.OtomAnalyze, isolated: true },
			{ action: ActionName.OtomMineAllOtoms, isolated: true },
			{ action: ActionName.OtomMineMolecule, isolated: true },
			{ action: ActionName.OtomMineOtom, isolated: true },
			{ action: ActionName.OtomMineAndAnnihilateMolecule, isolated: true },
			{ action: ActionName.OtomCraftPkax, isolated: true },
		],
	},
	{
		group: ActionsGroupName.Hemi,
		premium: true,
		actions: [{ action: ActionName.CheckStats, isolated: false }],
	},
	{
		group: ActionsGroupName.Plasma,
		premium: true,
		actions: [{ action: ActionName.Deposit, isolated: true }],
	},
	{
		group: ActionsGroupName.Sophon,
		premium: true,
		actions: [{ action: ActionName.Claim, isolated: true }],
	},
];
